
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package rubensweeper;

// <editor-fold defaultstate="collapsed" desc="Import Block"> 
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.ImageIcon;
// </editor-fold>


/**
 *
 * @author ruiz_854748
 */
public class MainWindow extends javax.swing.JFrame {

    Grid grid;
    MouseListener ml = // <editor-fold defaultstate="collapsed" desc="Mouse Listener for the MenuButton"> 
            new MouseListener() {

                    @Override
                    public void mouseClicked(MouseEvent e) {
                        startGame();
                    }

                    @Override
                    public void mousePressed(MouseEvent e) {
                        titleSlot.setIcon(new ImageIcon("clicky.png", "¯\\_(ツ)_/¯"));
                    }

                    @Override
                    public void mouseReleased(MouseEvent e) {
                        titleSlot.setIcon(new ImageIcon("start.png", "¯\\_(ツ)_/¯"));
                        //startGame();
                    }

                    @Override
                    public void mouseEntered(MouseEvent e) {
                        
                    }

                    @Override
                    public void mouseExited(MouseEvent e) {
                        
                    }
                };// </editor-fold>
    MouseListener winml = // <editor-fold defaultstate="collapsed" desc="Mouse Listener for the JPanel"> 
            new MouseListener() {

                    @Override
                    public void mouseClicked(MouseEvent e) {
                        gameWindow.removeAll();
                        startGame();
                        gameWindow.updateUI();
                        
                    }

                    @Override
                    public void mousePressed(MouseEvent e) {
                        titleSlot.setIcon(new ImageIcon("clicky.png", "¯\\_(ツ)_/¯"));
                    }

                    @Override
                    public void mouseReleased(MouseEvent e) {
                        titleSlot.setIcon(new ImageIcon("start.png", "¯\\_(ツ)_/¯"));
                        //startGame();
                    }

                    @Override
                    public void mouseEntered(MouseEvent e) {
                        
                    }

                    @Override
                    public void mouseExited(MouseEvent e) {
                        
                    }
                }; // </editor-fold>
    

    
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        
        
        initComponents();
        startGame();
        
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code"> 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleSlot = new Smiley();
        gameWindow = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        titleTextSlot = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        titleSlot.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        titleSlot.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(titleSlot, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleSlot, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        gameWindow.setBackground(new java.awt.Color(0, 204, 255));

        javax.swing.GroupLayout gameWindowLayout = new javax.swing.GroupLayout(gameWindow);
        gameWindow.setLayout(gameWindowLayout);
        gameWindowLayout.setHorizontalGroup(
            gameWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        gameWindowLayout.setVerticalGroup(
            gameWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Game Options");
        jMenuBar1.add(jMenu2);

        titleTextSlot.setText("                                                 ");
        titleTextSlot.setEnabled(false);
        jMenuBar1.add(titleTextSlot);

        jMenu4.setText("Time: 000");
        jMenu4.setEnabled(false);
        jMenuBar1.add(jMenu4);

        jMenu3.setText("Score: 0");
        jMenu3.setEnabled(false);
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(gameWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(gameWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // </editor-fold>
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            //for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            //    System.out.println(info.getName());
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
                
            //}
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Variable Declarations"> 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel gameWindow;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel titleSlot;
    private javax.swing.JMenu titleTextSlot;
    // End of variables declaration//GEN-END:variables
    // </editor-fold>
    
    
    private void initializeGrid() {
        
        gameWindow.setLayout(new GridBagLayout());
        
        for(int y = 0; y < grid.getVertLength(); y++){
            for(int x = 0; x < grid.getHorizLength(); x++) {
                GridBagConstraints c = new GridBagConstraints();
                
                c.gridx = x;
                c.gridy = y;
                c.weightx = 0;
                c.weighty = 0;
                
                Square sq = grid.getSquareAt(x, y);
                sq.setIcon(new ImageIcon("Closed-32.png", "¯\\_(ツ)_/¯"));
                gameWindow.add(sq, c);
                
                
                
                // This is where the mouse listener gets tied to a universal onClick Method to handle square selection
                sq.addMouseListener(grid.getDefaultSML());
            }
        }
    }

    private void startGame() {
        grid = new Grid(9,9);
        grid.startGame();
        grid.print();
        titleTextSlot.addMouseListener(ml);
        gameWindow.addMouseListener(winml);
        initializeGrid();
        
        
    }
    
}
    
    
    
    

